### ISSUE TITLE
Experiment5

### ISSUE THREAD

**Issue by quant2008** [tschm/cs#2]
Hi Dr. Schmelzer,
I have learned so much from your work, thank you very much.
I have a question in Experiment5, you say in conclusions 
"Possible to reflect trading costs in objective with regularization terms (Ridge, Lars, Elastic Nets, ...).

Could you give a small example of this regularization term?

**Comment by tschm** [comment]
Thank you. You can always tame an optimizer using penalty terms such as min 2-norm (Ax - b) will end up with large coefficients in x. A standard approach would be to apply Ridge regression, e.g. we solve a different but behaved problem, as in min 2-norm (Ax - b) + lambda * 2-norm (x) where lambda is a nonnegative parameter. The larger lambda the smaller the coefficients will be
