### ISSUE TITLE
what's the difference between p_hashed.csv and p_ob.csv?

### ISSUE THREAD

**Issue by quant2008** [tschm/cs#45]
Hello, I ran experitment5 against p_hashed.csv and p_ob.csv and get very different results. the result of p_hashed is very bad and the result of p_ob is very good. Just wonder what the difference between p_hashed.csv and p_ob.csv is?

**Comment by tschm** [comment]
I don't remember what the problem in p_ob.csv was. I guess something went wrong on their adjusting. p_hashed.csv is back adjusted data rolled 3 days prior to expiry and adjusted by ratio. I should remove p_ob.csv as I am not using it.
